version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true

volumes:
  postgres-data:
